/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,jsx}',
    './src/components/**/*.{js,jsx}',
    './src/app/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        obsidian: {
          950: '#06080E',
          900: '#090D16',
          800: '#0F1420',
          700: '#171F30',
          600: '#222C42',
        },
        accent: {
          DEFAULT: '#0284c7',
          light: '#38bdf8',
          glow: 'rgba(2, 132, 199, 0.15)',
        },
        // Stitch Surface & Material Design System Tokens
        'surface-bright': '#353942',
        'surface-tint': '#93ccff',
        'surface-variant': '#31353e',
        'outline': '#89929b',
        'secondary-container': '#0053db',
        'surface-container-high': '#262a33',
        'primary-fixed': '#cce5ff',
        'on-background': '#dfe2ee',
        'surface-dim': '#0f131c',
        'secondary-fixed': '#dbe1ff',
        'on-primary-fixed': '#001d31',
        'tertiary': '#ffb95f',
        'surface-container-highest': '#31353e',
        'on-secondary-container': '#cdd7ff',
        'on-primary': '#003351',
        'on-tertiary-fixed-variant': '#653e00',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary': '#472a00',
        'on-primary-container': '#002c47',
        'error': '#ffb4ab',
        'inverse-on-surface': '#2c3039',
        'secondary-fixed-dim': '#b4c5ff',
        'surface-container': '#1c2028',
        'surface-container-low': '#181c24',
        'on-error': '#690005',
        'primary-container': '#3198dc',
        'on-primary-fixed-variant': '#004b73',
        'inverse-surface': '#dfe2ee',
        'surface-container-lowest': '#0a0e16',
        'primary-fixed-dim': '#93ccff',
        'tertiary-fixed': '#ffddb8',
        'background': '#0f131c',
        'on-secondary-fixed-variant': '#003ea8',
        'secondary': '#b4c5ff',
        'on-tertiary-fixed': '#2a1700',
        'on-surface': '#dfe2ee',
        'inverse-primary': '#006398',
        'tertiary-container': '#ca8100',
        'on-surface-variant': '#bfc7d2',
        'on-tertiary-container': '#3e2400',
        'on-error-container': '#ffdad6',
        'surface': '#0f131c',
        'primary': '#93ccff',
        'on-secondary': '#002a78',
        'outline-variant': '#3f4850',
        'on-secondary-fixed': '#00174b',
      },
      spacing: {
        'space-xs': '0.25rem',
        'margin': '2rem',
        'space-xl': '2.5rem',
        'gutter-sm': '1rem',
        'gutter-lg': '2rem',
        'space-lg': '1.5rem',
        'gutter': '1.5rem',
        'margin-mobile': '1rem',
        'margin-desktop': '3rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-tag': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-code': ['JetBrains Mono', 'monospace'],
        'label-caption': ['Plus Jakarta Sans', 'sans-serif'],
        'display-hero': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-hero-mobile': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'label-tag': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-code': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-caption': ['11px', { lineHeight: '14px', letterSpacing: '0.01em', fontWeight: '500' }],
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '400' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

